import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type": "application/json", "Cache-Control": "private, max-age=900" } });
const fromB64 = (value: string) => Uint8Array.from(atob(value), (char) => char.charCodeAt(0));
async function decrypt(value: string, iv: string, key: CryptoKey) { return new TextDecoder().decode(await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromB64(iv) }, key, fromB64(value))); }
async function getJson(url: string, apiKey: string, apiSecret: string) { const response = await fetch(url, { headers: { "APCA-API-KEY-ID": apiKey, "APCA-API-SECRET-KEY": apiSecret } }); if (!response.ok) throw new Error(`Alpaca data error (${response.status})`); return response.json(); }
Deno.serve(async (request) => {
  if (request.method === "OPTIONS") return new Response("ok", { headers: cors });
  try {
    const admin = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!, { auth: { persistSession: false } }); const token = request.headers.get("Authorization")?.replace(/^Bearer\s+/i, ""); const { data: { user } } = await admin.auth.getUser(token); if (!user) return json({ error: "Authentication required" }, 401);
    const { data: connection } = await admin.from("bg_broker_connections").select("id").eq("user_id", user.id).eq("environment", "paper").eq("status", "connected").single(); const { data: credential } = await admin.from("bg_broker_credentials").select("*").eq("connection_id", connection.id).single(); const raw = fromB64(Deno.env.get("BG_CREDENTIALS_KEY") || ""); const key = await crypto.subtle.importKey("raw", raw, "AES-GCM", false, ["decrypt"]); const [apiKey, apiSecret] = await Promise.all([decrypt(credential.api_key_ciphertext, credential.api_key_iv, key), decrypt(credential.api_secret_ciphertext, credential.api_secret_iv, key)]);
    const active = await getJson("https://data.alpaca.markets/v1beta1/screener/stocks/most-actives?top=100&by=volume", apiKey, apiSecret); const candidates = (active.most_actives || []).map((item: any) => item.symbol).filter((symbol: string) => /^[A-Z]{1,5}$/.test(symbol)); if (!candidates.length) throw new Error("Alpaca returned no liquid symbols");
    const end = new Date(), start = new Date(); start.setUTCDate(start.getUTCDate() - 8); const barsUrl = new URL("https://data.alpaca.markets/v2/stocks/bars"); barsUrl.searchParams.set("symbols", candidates.join(",")); barsUrl.searchParams.set("timeframe", "1Day"); barsUrl.searchParams.set("start", start.toISOString()); barsUrl.searchParams.set("end", end.toISOString()); barsUrl.searchParams.set("feed", "iex"); barsUrl.searchParams.set("limit", "10000"); const weekly = await getJson(barsUrl.toString(), apiKey, apiSecret); const symbols = candidates.map((symbol: string) => ({ symbol, volume: (weekly.bars?.[symbol] || []).reduce((sum: number, bar: any) => sum + Number(bar.v || 0), 0) })).sort((a: any, b: any) => b.volume - a.volume).slice(0, 100).map((item: any) => item.symbol);
    const expiry = new Date(); expiry.setUTCDate(expiry.getUTCDate() + 60); const contractsUrl = new URL("https://paper-api.alpaca.markets/v2/options/contracts"); contractsUrl.searchParams.set("underlying_symbols", symbols.join(",")); contractsUrl.searchParams.set("expiration_date_lte", expiry.toISOString().slice(0, 10)); contractsUrl.searchParams.set("limit", "10000"); const contracts = await getJson(contractsUrl.toString(), apiKey, apiSecret); const optionSymbols = [...new Set((contracts.option_contracts || []).map((contract: any) => contract.underlying_symbol).filter(Boolean))];
    return json({ symbols, optionSymbols, periodStart: start.toISOString(), periodEnd: end.toISOString(), methodology: "Ranked by summed Alpaca IEX daily share volume over the previous eight calendar days from Alpaca's current 100 most-active candidates." });
  } catch (error) { return json({ error: error instanceof Error ? error.message : "Unable to rank liquid symbols" }, 500); }
});
