import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type": "application/json", "Cache-Control": "private, max-age=300" } });
const fromB64 = (value: string) => Uint8Array.from(atob(value), (char) => char.charCodeAt(0));
async function decrypt(value: string, iv: string, key: CryptoKey) { return new TextDecoder().decode(await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromB64(iv) }, key, fromB64(value))); }
async function getJson(url: string, apiKey: string, apiSecret: string) { const response = await fetch(url, { headers: { "APCA-API-KEY-ID": apiKey, "APCA-API-SECRET-KEY": apiSecret } }); if (!response.ok) throw new Error(`Alpaca data error (${response.status})`); return response.json(); }
const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0;

Deno.serve(async (request) => {
  if (request.method === "OPTIONS") return new Response("ok", { headers: cors });
  try {
    const body = await request.json().catch(() => ({})), allowedModes = new Set(["sustained_volume", "today_volume", "relative_volume", "active_movers"]), rankingMode = allowedModes.has(body.rankingMode) ? body.rankingMode : "sustained_volume";
    const admin = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!, { auth: { persistSession: false } }); const token = request.headers.get("Authorization")?.replace(/^Bearer\s+/i, ""); const { data: { user } } = await admin.auth.getUser(token); if (!user) return json({ error: "Authentication required" }, 401);
    const { data: connection } = await admin.from("bg_broker_connections").select("id").eq("user_id", user.id).eq("environment", "paper").eq("status", "connected").single(); if (!connection) return json({ error: "Connect Alpaca before loading a ticker universe" }, 400); const { data: credential } = await admin.from("bg_broker_credentials").select("*").eq("connection_id", connection.id).single(); const raw = fromB64(Deno.env.get("BG_CREDENTIALS_KEY") || ""); const key = await crypto.subtle.importKey("raw", raw, "AES-GCM", false, ["decrypt"]); const [apiKey, apiSecret] = await Promise.all([decrypt(credential.api_key_ciphertext, credential.api_key_iv, key), decrypt(credential.api_secret_ciphertext, credential.api_secret_iv, key)]);
    const active = await getJson("https://data.alpaca.markets/v1beta1/screener/stocks/most-actives?top=100&by=volume", apiKey, apiSecret); const candidates = (active.most_actives || []).map((item: any) => item.symbol).filter((symbol: string) => /^[A-Z]{1,5}$/.test(symbol)); if (!candidates.length) throw new Error("Alpaca returned no liquid symbols");
    const end = new Date(), start = new Date(); start.setUTCDate(start.getUTCDate() - 40); const barsUrl = new URL("https://data.alpaca.markets/v2/stocks/bars"); barsUrl.searchParams.set("symbols", candidates.join(",")); barsUrl.searchParams.set("timeframe", "1Day"); barsUrl.searchParams.set("start", start.toISOString()); barsUrl.searchParams.set("end", end.toISOString()); barsUrl.searchParams.set("feed", "iex"); barsUrl.searchParams.set("adjustment", "all"); barsUrl.searchParams.set("limit", "10000"); const history = await getJson(barsUrl.toString(), apiKey, apiSecret);
    const ranked = candidates.map((symbol: string) => { const bars = (history.bars?.[symbol] || []).slice(-21), latest = bars.at(-1), previous = bars.at(-2), prior = bars.slice(0, -1).slice(-20), averageVolume = average(prior.map((bar: any) => Number(bar.v || 0))), averageDollarVolume = average(prior.map((bar: any) => Number(bar.v || 0) * Number(bar.c || 0))), todayVolume = Number(latest?.v || 0), price = Number(latest?.c || 0), relativeVolume = averageVolume ? todayVolume / averageVolume : 0, movePct = previous ? (price / Number(previous.c) - 1) * 100 : 0, sustainedVolume = bars.slice(-5).reduce((sum: number, bar: any) => sum + Number(bar.v || 0), 0), todayDollarVolume = todayVolume * price; const scores: Record<string, number> = { sustained_volume: sustainedVolume, today_volume: todayVolume, relative_volume: relativeVolume, active_movers: Math.abs(movePct) }; return { symbol, price, average_dollar_volume: averageDollarVolume, today_dollar_volume: todayDollarVolume, today_volume: todayVolume, relative_volume: relativeVolume, move_pct: movePct, sustained_volume: sustainedVolume, score: scores[rankingMode] }; }).filter((item: any) => item.price >= 10 && item.average_dollar_volume >= 100_000_000 && item.today_dollar_volume >= 25_000_000);
    const eligible = (ranked.length >= 20 ? ranked : candidates.map((symbol: string) => { const bars = (history.bars?.[symbol] || []).slice(-21), latest = bars.at(-1), previous = bars.at(-2), prior = bars.slice(0, -1), averageVolume = average(prior.map((bar: any) => Number(bar.v || 0))), averageDollarVolume = average(prior.map((bar: any) => Number(bar.v || 0) * Number(bar.c || 0))), todayVolume = Number(latest?.v || 0), price = Number(latest?.c || 0), relativeVolume = averageVolume ? todayVolume / averageVolume : 0, movePct = previous ? (price / Number(previous.c) - 1) * 100 : 0, sustainedVolume = bars.slice(-5).reduce((sum: number, bar: any) => sum + Number(bar.v || 0), 0), scores: Record<string, number> = { sustained_volume: sustainedVolume, today_volume: todayVolume, relative_volume: relativeVolume, active_movers: Math.abs(movePct) }; return { symbol, price, average_dollar_volume: averageDollarVolume, today_dollar_volume: todayVolume * price, today_volume: todayVolume, relative_volume: relativeVolume, move_pct: movePct, sustained_volume: sustainedVolume, score: scores[rankingMode] }; }).filter((item: any) => item.price >= 5 && item.average_dollar_volume >= 25_000_000)).sort((a: any, b: any) => b.score - a.score).slice(0, 40);
    const symbols = eligible.map((item: any) => item.symbol); if (!symbols.length) throw new Error("No symbols passed the large/liquid safety proxy");
    const expiry = new Date(); expiry.setUTCDate(expiry.getUTCDate() + 60); const contractsUrl = new URL("https://paper-api.alpaca.markets/v2/options/contracts"); contractsUrl.searchParams.set("underlying_symbols", symbols.join(",")); contractsUrl.searchParams.set("expiration_date_lte", expiry.toISOString().slice(0, 10)); contractsUrl.searchParams.set("limit", "10000"); const contracts = await getJson(contractsUrl.toString(), apiKey, apiSecret); const optionSymbols = [...new Set((contracts.option_contracts || []).map((contract: any) => contract.underlying_symbol).filter(Boolean))];
    return json({ symbols, optionSymbols, ranked: eligible, rankingMode, candidateCount: candidates.length, eligibleCount: symbols.length, periodStart: start.toISOString(), periodEnd: end.toISOString(), methodology: "Random pool is the top 40 qualifying names for the selected ranking within Alpaca's current 100 most active. Primary safety proxy requires price >= $10, 20-session average dollar volume >= $100M, and latest-session dollar volume >= $25M; a relaxed liquid fallback is used only when fewer than 20 names qualify. This is a liquidity proxy, not verified market capitalization." });
  } catch (error) { return json({ error: error instanceof Error ? error.message : "Unable to rank liquid symbols" }, 500); }
});
