import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });
const fromB64 = (value: string) => Uint8Array.from(atob(value), (char) => char.charCodeAt(0));
async function cryptoKey() { const raw = fromB64(Deno.env.get("BG_CREDENTIALS_KEY") || ""); if (raw.length !== 32) throw new Error("Credential encryption is not configured"); return crypto.subtle.importKey("raw", raw, "AES-GCM", false, ["decrypt"]); }
async function decrypt(value: string, iv: string, key: CryptoKey) { return new TextDecoder().decode(await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromB64(iv) }, key, fromB64(value))); }
type Bar = { t: string; o: number; h: number; l: number; c: number; v: number; vw?: number };
const avg = (values: number[]) => values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0;
const sma = (bars: Bar[], period: number) => avg(bars.slice(-period).map((bar) => bar.c));
function ema(bars: Bar[], period: number) { const k = 2 / (period + 1); return bars.reduce((last, bar, i) => i ? bar.c * k + last * (1 - k) : bar.c, bars[0]?.c || 0); }
function rsi(bars: Bar[], period: number) { if (bars.length <= period) return 50; let gains = 0, losses = 0; for (let i = bars.length - period; i < bars.length; i++) { const d = bars[i].c - bars[i - 1].c; if (d >= 0) gains += d; else losses -= d; } return losses ? 100 - 100 / (1 + gains / losses) : 100; }
function atr(bars: Bar[], period: number) { return avg(bars.slice(-period).map((bar, i, tail) => i ? Math.max(bar.h - bar.l, Math.abs(bar.h - tail[i - 1].c), Math.abs(bar.l - tail[i - 1].c)) : bar.h - bar.l)); }
function percentileRank(values: number[], value: number) { return values.length ? values.filter((item) => item <= value).length / values.length * 100 : 50; }
function bandwidth(bars: Bar[], period: number) { const values = bars.slice(-period).map((bar) => bar.c), mean = avg(values), sd = Math.sqrt(avg(values.map((value) => (value - mean) ** 2))); return mean ? 4 * sd / mean * 100 : 0; }
function easternParts(timestamp: string) { const parts = new Intl.DateTimeFormat("en-US", { timeZone: "America/New_York", weekday: "short", hour: "2-digit", minute: "2-digit", hour12: false }).formatToParts(new Date(timestamp)); return Object.fromEntries(parts.map((part) => [part.type, part.value])); }
function matches(condition: any, bars: Bar[], context: { benchmarkBars?: Bar[] } = {}) {
  const p = condition.parameters || {}, bar = bars.at(-1)!; const op = (value: number, target: number) => p.operator === "above" ? value > target : value < target;
  if (condition.type === "immediate") return true;
  if(condition.type==="trailing_reversal"){const lookback=Math.max(3,Number(p.lookback_bars||18)),window=bars.slice(-lookback),peak=Math.max(...window.map(item=>item.h)),trough=Math.min(...window.map(item=>item.l)),pullback=(peak-trough)/peak*100,rebound=(bar.c-trough)/trough*100;return pullback>=Number(p.pullback_pct)&&rebound>=Number(p.rebound_pct);}
  if (condition.type === "price") return op(bar.c, Number(p.value));
  if (condition.type === "volume") return op(bar.v, Number(p.value));
  if (condition.type === "rsi") return op(rsi(bars, Number(p.period || 14)), Number(p.value));
  if (condition.type === "moving_average") { const calc = p.average === "sma" ? sma : ema; return op(calc(bars, Number(p.fast)), calc(bars, Number(p.slow))); }
  if (condition.type === "relative_volume") return op(bar.v / (avg(bars.slice(-(Number(p.lookback || 20) + 1), -1).map((b) => b.v)) || Infinity), Number(p.value));
  if (condition.type === "vwap") { const volume = bars.reduce((s, b) => s + b.v, 0); const vwap = bars.reduce((s, b) => s + (b.vw || b.c) * b.v, 0) / (volume || 1); return op(bar.c, vwap); }
  if (condition.type === "percent_change") { const anchor = p.anchor === "session_open" ? bars.find((b) => b.t.slice(0, 10) === bar.t.slice(0, 10))?.o : bars.at(-2)?.c; return op((bar.c / (anchor || bar.c) - 1) * 100, Number(p.value)); }
  if (condition.type === "atr") return op(atr(bars, Number(p.period || 14)) / bar.c * 100, Number(p.value));
  if (condition.type === "atr_percentile") { const period = Number(p.period || 14), lookback = Number(p.lookback || 60), samples = bars.slice(-lookback).map((_, index, tail) => atr(tail.slice(0, index + 1), period) / (tail[index]?.c || 1) * 100).filter(Number.isFinite); return op(percentileRank(samples, samples.at(-1) || 0), Number(p.value)); }
  if (condition.type === "bollinger_bandwidth") { const period = Number(p.period || 20), lookback = Number(p.lookback || 60), tail = bars.slice(-(lookback + period)), samples = tail.map((_, index) => bandwidth(tail.slice(0, index + 1), period)).slice(period - 1); return op(percentileRank(samples, samples.at(-1) || 0), Number(p.value)); }
  if (condition.type === "relative_strength") { const benchmark = context.benchmarkBars || [], lookback = Number(p.lookback || 12); if (bars.length <= lookback || benchmark.length <= lookback) return false; const own = (bar.c / bars.at(-(lookback + 1))!.c - 1) * 100, base = (benchmark.at(-1)!.c / benchmark.at(-(lookback + 1))!.c - 1) * 100; return op(own - base, Number(p.value || 0)); }
  if (condition.type === "market_regime") { const benchmark = context.benchmarkBars || []; if (!benchmark.length) return false; const bullish = ema(benchmark, Number(p.fast || 20)) > ema(benchmark, Number(p.slow || 50)); return p.operator === "bearish" ? !bullish : bullish; }
  if (condition.type === "macd") { const fast = Number(p.fast || 12), slow = Number(p.slow || 26), signalPeriod = Number(p.signal || 9), macdSeries = bars.map((_, index) => ema(bars.slice(0, index + 1), fast) - ema(bars.slice(0, index + 1), slow)), signalBars = macdSeries.map((value, index) => ({ ...bars[index], c: value })); const bullish = macdSeries.at(-1)! > ema(signalBars, signalPeriod); return p.operator === "bearish" ? !bullish : bullish; }
  if (condition.type === "bollinger") { const values = bars.slice(-Number(p.period || 20)).map((b) => b.c), mean = avg(values), sd = Math.sqrt(avg(values.map((v) => (v - mean) ** 2))), lower = mean - Number(p.deviations || 2) * sd, upper = mean + Number(p.deviations || 2) * sd; return p.operator === "below_lower" ? bar.c < lower : p.operator === "above_upper" ? bar.c > upper : p.operator === "above_lower" ? bar.c > lower : bar.c < upper; }
  if (condition.type === "opening_range") { const today = bars.filter((b) => b.t.slice(0, 10) === bar.t.slice(0, 10)), range = today.slice(0, Math.max(1, Number(p.minutes || 15) / 5)); return p.operator === "above" ? bar.c > Math.max(...range.map((b) => b.h)) : bar.c < Math.min(...range.map((b) => b.l)); }
  if (condition.type === "gap") { const date = bar.t.slice(0, 10), first = bars.findIndex((item) => item.t.slice(0, 10) === date); if (first <= 0) return false; const value = (bars[first].o / bars[first - 1].c - 1) * 100; return p.operator === "up" ? value >= Number(p.value) : value <= -Number(p.value); }
  if (condition.type === "session_breakout") { const today = bars.filter((item) => item.t.slice(0, 10) === bar.t.slice(0, 10)), prior = today.slice(0, -1); if (!prior.length) return false; const buffer = Number(p.buffer || 0) / 100; return p.operator === "above" ? bar.c > Math.max(...prior.map((item) => item.h)) * (1 + buffer) : bar.c < Math.min(...prior.map((item) => item.l)) * (1 - buffer); }
  if (condition.type === "candles") { const tail = bars.slice(-Number(p.count || 3)); return tail.length === Number(p.count || 3) && tail.every((item) => p.color === "green" ? item.c > item.o : item.c < item.o); }
  if (condition.type === "time_window") { const parts = easternParts(bar.t), time = `${parts.hour}:${parts.minute}`; return time >= String(p.start || "09:30") && time <= String(p.end || "15:45"); }
  if (condition.type === "weekday") { const day = easternParts(bar.t).weekday; return String(p.days || "").split(",").map((item) => item.trim()).includes(day); }
  return false;
}
async function alpaca(url: string, apiKey: string, apiSecret: string, init: RequestInit = {}) { const response = await fetch(url, { ...init, headers: { "APCA-API-KEY-ID": apiKey, "APCA-API-SECRET-KEY": apiSecret, "Content-Type": "application/json", ...(init.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || `Alpaca error ${response.status}`); return body; }
const datePlus = (days: number) => { const date = new Date(); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); };
function optionMeta(symbol: string) { const match = symbol.match(/(\d{6})([CP])(\d{8})$/); return match ? { expiry: match[1], type: match[2] === "C" ? "call" : "put", strike: Number(match[3]) / 1000 } : null; }
async function optionOrder(bot: any, bars: Bar[], apiKey: string, apiSecret: string, admin: any, clientOrderId: string) {
  const { data: config } = await admin.from("bg_option_spreads").select("*").eq("bot_id", bot.id).single(); if (!config) throw new Error("Option configuration is missing");
  const type = ["bull_put_credit", "bear_put_debit", "long_put"].includes(config.spread_type) ? "put" : "call";
  const url = new URL(`https://data.alpaca.markets/v1beta1/options/snapshots/${encodeURIComponent(bot.symbol)}`); url.searchParams.set("feed", "indicative"); url.searchParams.set("type", type); url.searchParams.set("expiration_date_gte", datePlus(config.min_dte)); url.searchParams.set("expiration_date_lte", datePlus(config.max_dte)); url.searchParams.set("limit", "1000");
  const payload = await alpaca(url.toString(), apiKey, apiSecret); const candidates = Object.entries(payload.snapshots || {}).map(([symbol, snapshot]: any) => { const meta = optionMeta(symbol); const quote = snapshot.latestQuote || snapshot.latest_quote || {}; return { symbol, ...meta, delta: Math.abs(Number(snapshot.greeks?.delta)), bid: Number(quote.bp || quote.bid_price), ask: Number(quote.ap || quote.ask_price) }; }).filter((item: any) => item.strike && item.delta && item.bid > 0 && item.ask > item.bid && ((item.ask - item.bid) / ((item.ask + item.bid) / 2) * 100) <= Number(config.max_bid_ask_pct));
  if (!candidates.length) throw new Error("No liquid option contracts matched the configured expiration window");
  const target = Number(config.short_delta_target); candidates.sort((a: any, b: any) => Math.abs(a.delta - target) - Math.abs(b.delta - target)); const primary: any = candidates[0]; const family = config.strategy_family || "credit_spread"; const qty = Number(config.contracts || 1);
  if (family === "long_option") { const maxQty = Math.floor(Number(bot.max_allocation) / (primary.ask * 100)); if (maxQty < 1) throw new Error("Selected option premium exceeds maximum risk"); return { request: { symbol: primary.symbol, qty: String(Math.min(qty, maxQty)), side: "buy", type: "limit", limit_price: primary.ask.toFixed(2), time_in_force: "day", position_intent: "buy_to_open", client_order_id: clientOrderId }, risk: Math.min(qty, maxQty) * primary.ask * 100, symbols: [primary.symbol] };
  }
  const width = Number(config.target_width), longPrimary = family === "debit_spread"; const partnerStrike = config.spread_type === "bull_call_debit" || config.spread_type === "bear_call_credit" ? primary.strike + width : primary.strike - width;
  const partners = candidates.filter((item: any) => item.expiry === primary.expiry && Math.abs(item.strike - partnerStrike) < .001); if (!partners.length) throw new Error("No matching protective leg was available at the configured width"); const partner: any = partners[0];
  const buy = longPrimary ? primary : partner, sell = longPrimary ? partner : primary; const debit = buy.ask - sell.bid, credit = sell.bid - buy.ask; if (family === "credit_spread" && credit < Number(config.target_premium || config.minimum_credit)) throw new Error("Available spread credit is below the configured minimum"); if (family === "debit_spread" && (debit <= 0 || debit > Number(config.target_premium || config.minimum_credit))) throw new Error("Available spread debit exceeds the configured maximum");
  const riskPer = family === "credit_spread" ? (width - credit) * 100 : debit * 100, maxQty = Math.floor(Number(bot.max_allocation) / riskPer); if (maxQty < 1) throw new Error("Selected spread exceeds maximum risk"); const orderQty = Math.min(qty, maxQty); const net = family === "credit_spread" ? -credit : debit;
  return { request: { order_class: "mleg", qty: String(orderQty), type: "limit", limit_price: net.toFixed(2), time_in_force: "day", client_order_id: clientOrderId, legs: [{ symbol: buy.symbol, ratio_qty: "1", side: "buy", position_intent: "buy_to_open" }, { symbol: sell.symbol, ratio_qty: "1", side: "sell", position_intent: "sell_to_open" }] }, risk: orderQty * riskPer, symbols: [buy.symbol, sell.symbol] };
}
async function manageOptionExit(bot: any, positions: any[], openOrders: any[], apiKey: string, apiSecret: string, admin: any) {
  const legs = positions.filter((position: any) => position.symbol?.startsWith(bot.symbol)); if (!legs.length) return { handled: false };
  const hasClosingOrder = openOrders.some((order: any) => order.position_intent?.endsWith("_to_close") || order.legs?.some((leg: any) => leg.position_intent?.endsWith("_to_close") && leg.symbol?.startsWith(bot.symbol))); if (hasClosingOrder) return { handled: true, waiting: true };
  const { data: config } = await admin.from("bg_option_spreads").select("*").eq("bot_id", bot.id).single(); if (!config) throw new Error("Option exit configuration is missing");
  const pnl = legs.reduce((sum: number, position: any) => sum + Number(position.unrealized_pl || 0), 0); const qty = Math.min(...legs.map((position: any) => Math.abs(Number(position.qty))));
  const entryPremium = Number(config.target_premium || config.minimum_credit) * 100 * qty; const profitTarget = entryPremium * Number(config.profit_close_pct) / 100; const lossLimit = Math.min(Number(config.max_risk), entryPremium * Number(config.loss_close_multiple));
  const expirations = legs.map((position: any) => optionMeta(position.symbol)?.expiry).filter(Boolean).map((value: string) => { const year = 2000 + Number(value.slice(0, 2)), month = Number(value.slice(2, 4)) - 1, day = Number(value.slice(4, 6)); return Date.UTC(year, month, day); }); const dte = expirations.length ? Math.ceil((Math.min(...expirations) - Date.now()) / 86400000) : 999;
  const reason = dte <= Number(config.exit_dte) ? "expiration_exit" : pnl >= profitTarget ? "profit_target" : pnl <= -lossLimit ? "loss_limit" : null; if (!reason) return { handled: true, monitored: true, unrealized_pnl: pnl, profit_target: profitTarget, loss_limit: lossLimit, dte };
  const bucket = Math.floor(Date.now() / 300000), clientOrderId = `bgx-${bot.id.slice(0, 12)}-${bucket}`; const prior = await fetch(`https://paper-api.alpaca.markets/v2/orders:by_client_order_id?client_order_id=${clientOrderId}`, { headers: { "APCA-API-KEY-ID": apiKey, "APCA-API-SECRET-KEY": apiSecret } }); if (prior.ok) return { handled: true, waiting: true };
  const closeLegs = legs.map((position: any) => { const isLong = Number(position.qty) > 0; return { symbol: position.symbol, ratio_qty: "1", side: isLong ? "sell" : "buy", position_intent: isLong ? "sell_to_close" : "buy_to_close" }; });
  const request = closeLegs.length === 1 ? { symbol: closeLegs[0].symbol, qty: String(qty), side: closeLegs[0].side, type: "market", time_in_force: "day", position_intent: closeLegs[0].position_intent, client_order_id: clientOrderId } : { order_class: "mleg", qty: String(qty), type: "market", time_in_force: "day", client_order_id: clientOrderId, legs: closeLegs };
  const order = await alpaca("https://paper-api.alpaca.markets/v2/orders", apiKey, apiSecret, { method: "POST", body: JSON.stringify(request) }); const { data: event } = await admin.from("bg_bot_events").select("run_id").eq("bot_id", bot.id).eq("event_type", "paper_order_submitted").order("created_at", { ascending: false }).limit(1).maybeSingle();
  const { data: trade } = event?.run_id ? await admin.from("bg_trades").select("id").eq("run_id", event.run_id).order("created_at", { ascending: false }).limit(1).maybeSingle() : { data: null }; await admin.from("bg_orders").insert({ trade_id: trade?.id || null, user_id: bot.user_id, broker_order_id: order.id, client_order_id: clientOrderId, symbol: bot.symbol, side: closeLegs[0].side, order_type: "market", quantity: qty, status: order.status, raw_response: order, submitted_at: new Date().toISOString() }); if (trade?.id) await admin.from("bg_trades").update({ status: "closing" }).eq("id", trade.id);
  await admin.from("bg_bot_events").insert({ bot_id: bot.id, run_id: event?.run_id || null, user_id: bot.user_id, event_type: "paper_exit_submitted", message: `Submitted ${bot.symbol} option exit: ${reason.replaceAll("_", " ")}`, details: { broker_order_id: order.id, client_order_id: clientOrderId, reason, unrealized_pnl: pnl, profit_target: profitTarget, loss_limit: lossLimit, dte } }); return { handled: true, exited: true, reason, broker_order_id: order.id };
}

async function runAdaptiveGrid(bot:any,apiKey:string,apiSecret:string,admin:any,prior:any){
  const{data:grid}=await admin.from("bg_grid_configs").select("*").eq("bot_id",bot.id).single();if(!grid)throw new Error("Crypto grid configuration is missing");
  const isCrypto=bot.asset_class==="crypto",url=isCrypto?new URL("https://data.alpaca.markets/v1beta3/crypto/us/latest/bars"):new URL(`https://data.alpaca.markets/v2/stocks/${encodeURIComponent(bot.symbol)}/bars/latest`);if(isCrypto)url.searchParams.set("symbols",bot.symbol);else url.searchParams.set("feed","iex");const payload=await alpaca(url.toString(),apiKey,apiSecret);const bar=isCrypto?payload.bars?.[bot.symbol]:payload.bar;const price=Number(bar?.c||0);if(!price)throw new Error("No current market price is available");
  const levels=Array.from({length:Number(grid.grid_levels)},(_,i)=>Number(grid.lower_price)*Math.pow(Number(grid.upper_price)/Number(grid.lower_price),i/(Number(grid.grid_levels)-1)));const index=Math.max(0,Math.min(levels.length-1,levels.findIndex(level=>price<=level)===-1?levels.length-1:levels.findIndex(level=>price<=level)));const previous=Number(prior?.details?.grid_index);
  if(!Number.isFinite(previous))return{reason_code:"grid_initialized",message:`Grid initialized at level ${index+1} of ${levels.length}`,details:{grid_index:index,last_price:price,lower_price:Number(grid.lower_price),upper_price:Number(grid.upper_price)},submitted:false};
  if(index===previous)return{reason_code:"grid_waiting",message:`Price remains in grid band ${index+1} of ${levels.length}`,details:{grid_index:index,last_price:price},submitted:false};
  const side=index<previous?"buy":"sell",clientOrderId=`bgc-${bot.id.slice(0,12)}-${Math.floor(Date.now()/300000)}`;let request:any={symbol:bot.symbol,side,type:"market",time_in_force:isCrypto?"gtc":"day",client_order_id:clientOrderId};
  if(side==="buy")request.notional=Math.min(Number(grid.order_amount),Number(bot.max_allocation)).toFixed(2);else{const positions=await alpaca("https://paper-api.alpaca.markets/v2/positions",apiKey,apiSecret);const position=positions.find((item:any)=>item.symbol===bot.symbol||item.symbol===bot.symbol.replace("/",""));const qty=Math.min(Number(position?.qty||0),Number(grid.order_amount)/price);if(qty<=0)return{reason_code:"grid_sell_skipped",message:"An upper grid level crossed, but no crypto inventory is available to sell",details:{grid_index:index,last_price:price},submitted:false};request.qty=qty.toFixed(8)}
  const order=await alpaca("https://paper-api.alpaca.markets/v2/orders",apiKey,apiSecret,{method:"POST",body:JSON.stringify(request)});await admin.from("bg_orders").insert({user_id:bot.user_id,broker_order_id:order.id,client_order_id:clientOrderId,symbol:bot.symbol,side,order_type:"market",notional:side==="buy"?Number(grid.order_amount):null,quantity:side==="sell"?Number(request.qty):null,status:order.status,raw_response:order,submitted_at:new Date().toISOString()});await admin.from("bg_bot_events").insert({bot_id:bot.id,user_id:bot.user_id,event_type:"paper_order_submitted",message:`Submitted ${bot.symbol} adaptive grid ${side}`,details:{broker_order_id:order.id,grid_index:index,last_price:price}});return{reason_code:"order_submitted",message:`Submitted adaptive grid ${side} at level ${index+1}`,details:{grid_index:index,last_price:price,broker_order_id:order.id},submitted:true};
}
async function cryptoRiskExit(bot:any,position:any,apiKey:string,apiSecret:string,admin:any){
  if(!position)return null;const policy=bot.start_condition?.strategy_config?.exit_policy||{},price=Number(position.current_price||0),average=Number(position.avg_entry_price||0),pnlPct=Number(position.unrealized_plpc||0)*100;const{data:saved}=await admin.from("bg_position_risk_state").select("*").eq("bot_id",bot.id).maybeSingle(),firstSeen=saved?.first_seen_at||new Date().toISOString(),high=Math.max(Number(saved?.high_water_price||price),price),gain=average?(high/average-1)*100:0,draw=high?(high-price)/high*100:0,hours=(Date.now()-new Date(firstSeen).valueOf())/3600000;await admin.from("bg_position_risk_state").upsert({bot_id:bot.id,user_id:bot.user_id,first_seen_at:firstSeen,high_water_price:high,updated_at:new Date().toISOString()});let reason="";if(bot.take_profit_pct&&pnlPct>=Number(bot.take_profit_pct))reason="profit_target";else if(bot.stop_loss_pct&&pnlPct<=-Number(bot.stop_loss_pct))reason="stop_loss";else if(gain>=Number(policy.trailing_activation_pct||999)&&draw>=Number(policy.trailing_distance_pct||999))reason="trailing_profit";else if(gain>=Number(policy.break_even_trigger_pct||999)&&pnlPct<=Number(policy.break_even_floor_pct||0))reason="break_even_protection";else if(hours>=Number(policy.max_hold_hours||Infinity))reason="maximum_hold_time";if(!reason)return null;const request={symbol:bot.symbol,qty:String(Math.abs(Number(position.qty))),side:"sell",type:"market",time_in_force:"gtc",client_order_id:`bgrx-${bot.id.slice(0,11)}-${Math.floor(Date.now()/300000)}`},order=await alpaca("https://paper-api.alpaca.markets/v2/orders",apiKey,apiSecret,{method:"POST",body:JSON.stringify(request)});await admin.from("bg_position_risk_state").delete().eq("bot_id",bot.id);await admin.from("bg_bot_events").insert({bot_id:bot.id,user_id:bot.user_id,event_type:"paper_exit_submitted",message:`Submitted ${bot.symbol} crypto ${reason.replaceAll("_"," ")} exit`,details:{broker_order_id:order.id,reason,unrealized_pnl_pct:pnlPct}});return{reason_code:"exit_submitted",message:`Submitted crypto ${reason.replaceAll("_"," ")} exit`,details:{broker_order_id:order.id,reason,unrealized_pnl_pct:pnlPct,high_water_price:high,drawdown_from_high_pct:draw,holding_hours:hours},submitted:true};
}
async function cryptoEntrySafety(bot:any,positions:any[],apiKey:string,apiSecret:string){const policy=bot.start_condition?.strategy_config?.exit_policy||{},account=await alpaca("https://paper-api.alpaca.markets/v2/account",apiKey,apiSecret),equity=Number(account.equity||0),last=Number(account.last_equity||equity),daily=last?(equity/last-1)*100:0;if(daily<=-Number(policy.max_daily_drawdown_pct||999))return{reason_code:"daily_drawdown_gate",message:"Account drawdown gate blocks new crypto entries",details:{daily_pnl_pct:daily}};const exposure=positions.filter((p:any)=>p.asset_class==="crypto").reduce((sum:number,p:any)=>sum+Math.abs(Number(p.market_value||0)),0),exposurePct=equity?exposure/equity*100:0;if(exposurePct>=Number(policy.max_crypto_exposure_pct||100))return{reason_code:"portfolio_exposure_gate",message:"Crypto portfolio exposure limit blocks a new entry",details:{crypto_exposure_pct:exposurePct}};const url=new URL("https://data.alpaca.markets/v1beta3/crypto/us/latest/quotes");url.searchParams.set("symbols",bot.symbol);const payload=await alpaca(url.toString(),apiKey,apiSecret),quote=payload.quotes?.[bot.symbol],bid=Number(quote?.bp||0),ask=Number(quote?.ap||0),spread=bid&&ask?(ask-bid)/((ask+bid)/2)*100:999;if(spread>Number(policy.max_spread_pct||1))return{reason_code:"spread_gate",message:"Live crypto spread is too wide for this strategy",details:{spread_pct:spread,max_spread_pct:Number(policy.max_spread_pct||1)}};return null;}
async function stockRiskExit(bot:any,position:any,apiKey:string,apiSecret:string,admin:any){if(!position)return null;const policy=bot.start_condition?.exit_policy||bot.start_condition?.strategy_config?.exit_policy||{trailing_activation_pct:3,trailing_distance_pct:1.5,break_even_trigger_pct:2,break_even_floor_pct:.1,max_hold_hours:72},price=Number(position.current_price||0),average=Number(position.avg_entry_price||0),pnlPct=Number(position.unrealized_plpc||0)*100,{data:saved}=await admin.from("bg_position_risk_state").select("*").eq("bot_id",bot.id).maybeSingle(),firstSeen=saved?.first_seen_at||new Date().toISOString(),high=Math.max(Number(saved?.high_water_price||price),price),gain=average?(high/average-1)*100:0,draw=high?(high-price)/high*100:0,hours=(Date.now()-new Date(firstSeen).valueOf())/3600000;await admin.from("bg_position_risk_state").upsert({bot_id:bot.id,user_id:bot.user_id,first_seen_at:firstSeen,high_water_price:high,updated_at:new Date().toISOString()});let reason="";if(bot.take_profit_pct&&pnlPct>=Number(bot.take_profit_pct))reason="profit_target";else if(bot.stop_loss_pct&&pnlPct<=-Number(bot.stop_loss_pct))reason="stop_loss";else if(gain>=Number(policy.trailing_activation_pct)&&draw>=Number(policy.trailing_distance_pct))reason="trailing_profit";else if(gain>=Number(policy.break_even_trigger_pct)&&pnlPct<=Number(policy.break_even_floor_pct))reason="break_even_protection";else if(hours>=Number(policy.max_hold_hours))reason="maximum_hold_time";if(!reason)return null;const request={symbol:bot.symbol,qty:String(Math.abs(Number(position.qty))),side:Number(position.qty)>0?"sell":"buy",type:"market",time_in_force:"day",client_order_id:`bgsx-${bot.id.slice(0,11)}-${Math.floor(Date.now()/300000)}`},order=await alpaca("https://paper-api.alpaca.markets/v2/orders",apiKey,apiSecret,{method:"POST",body:JSON.stringify(request)});await admin.from("bg_position_risk_state").delete().eq("bot_id",bot.id);await admin.from("bg_bot_events").insert({bot_id:bot.id,user_id:bot.user_id,event_type:"paper_exit_submitted",message:`Submitted ${bot.symbol} stock ${reason.replaceAll("_"," ")} exit`,details:{broker_order_id:order.id,reason,unrealized_pnl_pct:pnlPct}});return{reason_code:"exit_submitted",message:`Submitted stock ${reason.replaceAll("_"," ")} exit`,details:{broker_order_id:order.id,reason,unrealized_pnl_pct:pnlPct},submitted:true};}
async function runCryptoSignal(bot:any,apiKey:string,apiSecret:string,admin:any,prior:any){
  const strategy=bot.start_condition?.generated_strategy,config=bot.start_condition?.strategy_config||{},positions=await alpaca("https://paper-api.alpaca.markets/v2/positions",apiKey,apiSecret),position=positions.find((p:any)=>p.symbol===bot.symbol||p.symbol===bot.symbol.replace("/","")),exposure=Math.abs(Number(position?.market_value||0));
  const managedRisk=await cryptoRiskExit(bot,position,apiKey,apiSecret,admin);if(managedRisk)return managedRisk;
  if(position&&strategy!=="crypto_scheduled_accumulation"){const pnlPct=Number(position.unrealized_plpc||0)*100,target=Number(bot.take_profit_pct||0),stop=Number(bot.stop_loss_pct||0);if((target&&pnlPct>=target)||(stop&&pnlPct<=-stop)){const reason=pnlPct>=target?"profit_target":"stop_loss",request={symbol:bot.symbol,qty:String(Math.abs(Number(position.qty))),side:"sell",type:"market",time_in_force:"gtc",client_order_id:`bgcx-${bot.id.slice(0,11)}-${Math.floor(Date.now()/300000)}`},order=await alpaca("https://paper-api.alpaca.markets/v2/orders",apiKey,apiSecret,{method:"POST",body:JSON.stringify(request)});return{reason_code:"exit_submitted",message:`Submitted crypto ${reason.replaceAll("_"," ")} exit`,details:{broker_order_id:order.id,unrealized_pnl_pct:pnlPct},submitted:true};}return{reason_code:"position_monitored",message:"Crypto position open; profit and loss exits not reached",details:{unrealized_pnl_pct:pnlPct,profit_target_pct:target,stop_loss_pct:stop},submitted:false};}
  if(position&&strategy==="crypto_scheduled_accumulation"){const pnlPct=Number(position.unrealized_plpc||0)*100,target=Number(bot.take_profit_pct||0),stop=Number(bot.stop_loss_pct||0);if((target&&pnlPct>=target)||(stop&&pnlPct<=-stop)){const reason=pnlPct>=target?"profit_target":"stop_loss",request={symbol:bot.symbol,qty:String(Math.abs(Number(position.qty))),side:"sell",type:"market",time_in_force:"gtc",client_order_id:`bgca-${bot.id.slice(0,11)}-${Math.floor(Date.now()/300000)}`},order=await alpaca("https://paper-api.alpaca.markets/v2/orders",apiKey,apiSecret,{method:"POST",body:JSON.stringify(request)});return{reason_code:"exit_submitted",message:`Submitted accumulator ${reason.replaceAll("_"," ")} exit`,details:{broker_order_id:order.id,unrealized_pnl_pct:pnlPct},submitted:true};}}
  if(strategy==="crypto_scheduled_accumulation"){const interval=Number(config.interval_hours||24)*3600000,last=Number(prior?.details?.last_order_at||0);if(last&&Date.now()-last<interval)return{reason_code:"schedule_waiting",message:"Waiting for the next accumulation interval",details:{last_order_at:last,next_order_at:last+interval,current_exposure:exposure},submitted:false};}
  else if(position)return{reason_code:"existing_exposure",message:"Existing crypto position blocks another trailing entry",details:{current_exposure:exposure},submitted:false};
  const start=new Date(Date.now()-3*86400000).toISOString(),url=new URL("https://data.alpaca.markets/v1beta3/crypto/us/bars");url.searchParams.set("symbols",bot.symbol);url.searchParams.set("timeframe","5Min");url.searchParams.set("start",start);url.searchParams.set("limit","1000");const payload=await alpaca(url.toString(),apiKey,apiSecret),bars:Bar[]=payload.bars?.[bot.symbol]||[];if(bars.length<30)throw new Error("Not enough crypto bars to evaluate strategy");
  const conditions=bot.start_condition?.conditions||[],passed=conditions.length&&(bot.start_condition?.operator==="OR"?conditions.some((c:any)=>matches(c,bars)):conditions.every((c:any)=>matches(c,bars)));if(!passed)return{reason_code:"conditions_not_met",message:"Crypto entry conditions are not met",details:{last_price:bars.at(-1)?.c},submitted:false};const minEdge=Number(config.min_edge_bps||0),modeledEdge=Number(bot.take_profit_pct||0)*100;if(minEdge&&modeledEdge<minEdge+50)return{reason_code:"cost_gate",message:"Modeled move is too small relative to the fee and spread buffer",details:{modeled_edge_bps:modeledEdge,required_edge_bps:minEdge+50,last_price:bars.at(-1)?.c},submitted:false};
  const safety=await cryptoEntrySafety(bot,positions,apiKey,apiSecret);if(safety)return{...safety,submitted:false};const installments=Number(config.installments||1),scale=Number(config.volatility_scale||1)*Number(config.accelerated_dip_size||1),remaining=Math.max(0,Number(bot.max_allocation)-exposure),notional=Math.min(remaining,Number(bot.max_allocation)/installments*scale);if(notional<1)return{reason_code:"allocation_full",message:"Maximum crypto allocation is already deployed",details:{current_exposure:exposure},submitted:false};
  const clientOrderId=`bgcs-${bot.id.slice(0,11)}-${Math.floor(Date.now()/300000)}`,request={symbol:bot.symbol,notional:notional.toFixed(2),side:"buy",type:"market",time_in_force:"gtc",client_order_id:clientOrderId},order=await alpaca("https://paper-api.alpaca.markets/v2/orders",apiKey,apiSecret,{method:"POST",body:JSON.stringify(request)});await admin.from("bg_bot_events").insert({bot_id:bot.id,user_id:bot.user_id,event_type:"paper_order_submitted",message:`Submitted ${bot.symbol} ${strategy.replaceAll("_"," ")} buy`,details:{broker_order_id:order.id,notional}});return{reason_code:"order_submitted",message:"Submitted crypto paper buy",details:{broker_order_id:order.id,last_order_at:Date.now(),notional,last_price:bars.at(-1)?.c},submitted:true};
}
async function runCryptoDca(bot:any,apiKey:string,apiSecret:string,admin:any,prior:any){
  const [positions,{data:steps}]=await Promise.all([alpaca("https://paper-api.alpaca.markets/v2/positions",apiKey,apiSecret),admin.from("bg_averaging_steps").select("*").eq("bot_id",bot.id).order("step_number")]),position=positions.find((p:any)=>p.symbol===bot.symbol||p.symbol===bot.symbol.replace("/",""));
  const url=new URL("https://data.alpaca.markets/v1beta3/crypto/us/bars");url.searchParams.set("symbols",bot.symbol);url.searchParams.set("timeframe","5Min");url.searchParams.set("start",new Date(Date.now()-3*86400000).toISOString());url.searchParams.set("limit","1000");const payload=await alpaca(url.toString(),apiKey,apiSecret),bars:Bar[]=payload.bars?.[bot.symbol]||[],price=Number(bars.at(-1)?.c||0);if(bars.length<30||!price)throw new Error("Not enough crypto bars for DCA evaluation");
  const managedRisk=await cryptoRiskExit(bot,position,apiKey,apiSecret,admin);if(managedRisk)return managedRisk;
  let side="buy",notional=0,qty:any=null,reason="base_order",safetyCount=Number(prior?.details?.safety_count||0),basePrice=Number(prior?.details?.base_price||position?.avg_entry_price||price);
  if(position){const pnlPct=Number(position.unrealized_plpc||0)*100;if(pnlPct>=Number(bot.take_profit_pct||0)||pnlPct<=-Number(bot.stop_loss_pct||999)){side="sell";qty=String(Math.abs(Number(position.qty)));reason=pnlPct>=Number(bot.take_profit_pct||0)?"take_profit":"stop_loss";}else{const next=steps?.[safetyCount+1];if(!next)return{reason_code:"safety_orders_complete",message:"All safety orders are deployed; monitoring the blended exit",details:{safety_count:safetyCount,base_price:basePrice,last_price:price,unrealized_pnl_pct:pnlPct},submitted:false};const trigger=basePrice*(1-Number(next.deviation_pct)/100);if(price>trigger)return{reason_code:"dca_monitoring",message:`Waiting for safety order ${safetyCount+1} or blended exit`,details:{safety_count:safetyCount,base_price:basePrice,last_price:price,next_safety_price:trigger,unrealized_pnl_pct:pnlPct},submitted:false};notional=Number(next.order_amount);reason="safety_order";safetyCount++;}}
  else{const conditions=bot.start_condition?.conditions||[],passed=conditions.length&&(bot.start_condition?.operator==="OR"?conditions.some((c:any)=>matches(c,bars)):conditions.every((c:any)=>matches(c,bars)));if(!passed)return{reason_code:"conditions_not_met",message:"DCA base-order condition is not met",details:{last_price:price},submitted:false};notional=Number(steps?.[0]?.order_amount||bot.max_allocation);basePrice=price;safetyCount=0;}
  const clientOrderId=`bgcd-${bot.id.slice(0,11)}-${Math.floor(Date.now()/300000)}`,request:any={symbol:bot.symbol,side,type:"market",time_in_force:"gtc",client_order_id:clientOrderId};if(side==="buy")request.notional=Math.min(notional,Number(bot.max_allocation)).toFixed(2);else request.qty=qty;const order=await alpaca("https://paper-api.alpaca.markets/v2/orders",apiKey,apiSecret,{method:"POST",body:JSON.stringify(request)});await admin.from("bg_bot_events").insert({bot_id:bot.id,user_id:bot.user_id,event_type:side==="sell"?"paper_exit_submitted":"paper_order_submitted",message:`Submitted ${bot.symbol} DCA ${reason.replaceAll("_"," ")}`,details:{broker_order_id:order.id,safety_count:safetyCount,base_price:basePrice,last_price:price}});return{reason_code:side==="sell"?"exit_submitted":"order_submitted",message:`Submitted DCA ${reason.replaceAll("_"," ")}`,details:{broker_order_id:order.id,safety_count:safetyCount,base_price:basePrice,last_price:price},submitted:true};
}

Deno.serve(async (request) => {
  if (request.headers.get("x-runner-secret") !== Deno.env.get("BG_RUNNER_SECRET")) return json({ error: "Unauthorized" }, 401);
  const requestBody = await request.json().catch(() => ({})); const validateOptions = requestBody.validateOptions === true, exitOnly = requestBody.exitOnly === true;
  const admin = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!, { auth: { persistSession: false } });
  const summary = { mode: exitOnly ? "risk-monitor" : "entry-runner", checked: 0, matched: 0, submitted: 0, exits: 0, optionOrders: 0, optionExits: 0, optionValidated: 0, skipped: 0, errors: 0 };
  const { data: authUsers } = await admin.auth.admin.listUsers({ page: 1, perPage: 1000 }); const superuser = authUsers?.users?.find((user: any) => user.email?.toLowerCase() === "joeydavis0068@gmail.com");
  let regularQuery = admin.from("bg_bots").select("*").eq("environment", "paper"); regularQuery = exitOnly ? regularQuery.in("status", ["active", "paused"]) : regularQuery.eq("status", "active"); if (superuser) regularQuery = regularQuery.neq("user_id", superuser.id); let superQuery = superuser ? admin.from("bg_bots").select("*").eq("environment", "paper").eq("user_id", superuser.id) : null; if (superQuery) superQuery = exitOnly ? superQuery.in("status", ["active", "paused"]) : superQuery.eq("status", "active"); const [{ data: regularBots, error }, superResult] = await Promise.all([regularQuery.limit(100), superQuery || Promise.resolve({ data: [] })]); if (error) return json({ error: error.message }, 500); const bots = [...(superResult.data || []), ...(regularBots || [])];
  const key = await cryptoKey();
  const brokerCache = new Map<string, any>();
  for (const bot of bots || []) {
    summary.checked++;
    const cycleId = String(Math.floor(Date.now() / 300000)); const {data:priorStatus}=await admin.from("bg_bot_status").select("details").eq("bot_id",bot.id).maybeSingle(); const setStatus = (reason_code: string, message: string, details: any = {}) => admin.from("bg_bot_status").upsert({ bot_id: bot.id, user_id: bot.user_id, cycle_id: cycleId, reason_code, message, details, checked_at: new Date().toISOString() });
    try {
      await setStatus("checking", "Evaluation in progress");
      if (validateOptions && bot.asset_class !== "option") continue;
      let broker = brokerCache.get(bot.user_id);
      if (broker === undefined) {
        const { data: connection } = await admin.from("bg_broker_connections").select("id").eq("user_id", bot.user_id).eq("environment", "paper").eq("status", "connected").maybeSingle();
        if (!connection) broker = null;
        else {
          const { data: credential } = await admin.from("bg_broker_credentials").select("*").eq("connection_id", connection.id).single();
          const [apiKey, apiSecret] = await Promise.all([decrypt(credential.api_key_ciphertext, credential.api_key_iv, key), decrypt(credential.api_secret_ciphertext, credential.api_secret_iv, key)]);
          broker = { apiKey, apiSecret };
        }
        brokerCache.set(bot.user_id, broker);
      }
      if (!broker) { await setStatus("no_connection", "Waiting for a connected Alpaca paper account"); summary.skipped++; continue; }
      const { apiKey, apiSecret } = broker;
      if (exitOnly) {
        if (!broker.positions) [broker.positions, broker.openOrders] = await Promise.all([alpaca("https://paper-api.alpaca.markets/v2/positions", apiKey, apiSecret), alpaca("https://paper-api.alpaca.markets/v2/orders?status=open&nested=true&limit=500", apiKey, apiSecret)]);
        const positions = broker.positions, openOrders = broker.openOrders;
        const position = bot.asset_class === "option" ? null : positions.find((item: any) => item.symbol === bot.symbol || item.symbol === bot.symbol.replace("/", ""));
        const pendingForSymbol = openOrders.some((order: any) => order.symbol === bot.symbol || order.symbol === bot.symbol.replace("/", "") || order.legs?.some((leg: any) => leg.symbol?.startsWith(bot.symbol)));
        if (bot.asset_class !== "option" && !position) { summary.skipped++; continue; }
        if (pendingForSymbol) { await setStatus("exit_order_pending", "Risk monitor found an open order; waiting before another exit", { monitored_every_seconds: 60 }); summary.skipped++; continue; }
        let managed: any = null;
        if (bot.asset_class === "option") managed = await manageOptionExit(bot, positions, openOrders, apiKey, apiSecret, admin);
        else if (bot.asset_class === "crypto") managed = await cryptoRiskExit(bot, position, apiKey, apiSecret, admin);
        else managed = await stockRiskExit(bot, position, apiKey, apiSecret, admin);
        if (managed?.exited || managed?.submitted || managed?.reason_code === "exit_submitted") {
          const brokerOrderId = managed.details?.broker_order_id || managed.broker_order_id; if (brokerOrderId) openOrders.push({ id: brokerOrderId, symbol: bot.symbol });
          await setStatus("exit_submitted", managed.message || `Submitted ${bot.symbol} risk exit`, { ...managed.details, monitored_every_seconds: 60 }); summary.submitted++; summary.exits++; if (bot.asset_class === "option") summary.optionExits++;
        } else if (managed?.waiting) await setStatus("exit_pending", "A closing order is already pending", { ...managed, monitored_every_seconds: 60 });
        else if (managed?.handled || position) await setStatus("risk_monitoring", "One-minute risk monitor checked the open position; no exit threshold was reached", { unrealized_pnl_pct: position ? Number(position.unrealized_plpc || 0) * 100 : null, monitored_every_seconds: 60 });
        summary.skipped++; continue;
      }
      if(bot.asset_class==="crypto"&&!validateOptions){const result=bot.start_condition?.generated_strategy==="crypto_dca"?await runCryptoDca(bot,apiKey,apiSecret,admin,priorStatus):bot.bot_type==="grid"?await runAdaptiveGrid(bot,apiKey,apiSecret,admin,priorStatus):await runCryptoSignal(bot,apiKey,apiSecret,admin,priorStatus);await setStatus(result.reason_code,result.message,result.details);if(result.submitted){summary.submitted++;summary.matched++;}else summary.skipped++;continue;}
      const clock = await alpaca("https://paper-api.alpaca.markets/v2/clock", apiKey, apiSecret); if (!clock.is_open && !validateOptions) { await setStatus("market_closed", `Market closed; next open ${clock.next_open || "pending"}`, { next_open: clock.next_open }); summary.skipped++; continue; }
      if(bot.asset_class==="equity"&&bot.start_condition?.strategy_config?.exit_policy&&!validateOptions){const currentPositions=await alpaca("https://paper-api.alpaca.markets/v2/positions",apiKey,apiSecret),position=currentPositions.find((p:any)=>p.symbol===bot.symbol),managed=await stockRiskExit(bot,position,apiKey,apiSecret,admin);if(managed){await setStatus(managed.reason_code,managed.message,managed.details);summary.submitted++;continue;}}
      if(bot.asset_class==="equity"&&bot.bot_type==="grid"&&!validateOptions){const result=await runAdaptiveGrid(bot,apiKey,apiSecret,admin,priorStatus);await setStatus(result.reason_code,result.message,result.details);if(result.submitted){summary.submitted++;summary.matched++;}else summary.skipped++;continue;}
      const [positions, openOrders] = await Promise.all([alpaca("https://paper-api.alpaca.markets/v2/positions", apiKey, apiSecret), alpaca("https://paper-api.alpaca.markets/v2/orders?status=open&nested=true&limit=500", apiKey, apiSecret)]); if (bot.asset_class === "option" && !validateOptions) { const managed = await manageOptionExit(bot, positions, openOrders, apiKey, apiSecret, admin); if (managed.exited) { summary.optionExits++; await setStatus("exit_submitted", `Exit submitted: ${managed.reason.replaceAll("_", " ")}`, managed); } else if (managed.waiting) await setStatus("exit_pending", "A closing order is already pending", managed); else if (managed.monitored) await setStatus("position_monitored", "Position open; profit, loss, and DTE exits not reached", managed); if (managed.handled) { summary.skipped++; continue; } } const hasExposure = positions.some((p: any) => p.symbol === bot.symbol || (bot.asset_class === "option" && p.symbol.startsWith(bot.symbol))) || openOrders.some((o: any) => o.symbol === bot.symbol || (bot.asset_class === "option" && o.legs?.some((leg: any) => leg.symbol?.startsWith(bot.symbol)))); if (hasExposure && bot.start_condition?.generated_strategy!=="scheduled_accumulation" && !validateOptions) { await setStatus("existing_exposure", "Existing position or open order blocks a new entry"); summary.skipped++; continue; }
      const conditions = bot.start_condition?.conditions || []; const timeframe = conditions[0]?.timeframe || "5Min"; const start = new Date(Date.now() - 7 * 86400000).toISOString();
      const url = new URL(`https://data.alpaca.markets/v2/stocks/${encodeURIComponent(bot.symbol)}/bars`); url.searchParams.set("timeframe", timeframe); url.searchParams.set("start", start); url.searchParams.set("limit", "1000"); url.searchParams.set("feed", "iex");
      const bars: Bar[] = (await alpaca(url.toString(), apiKey, apiSecret)).bars || []; if (bars.length < 30) throw new Error("Not enough bars to evaluate conditions");
      const benchmarkCondition = conditions.find((condition: any) => ["relative_strength", "market_regime"].includes(condition.type)); let benchmarkBars: Bar[] = [];
      if (benchmarkCondition) { const benchmark = String(benchmarkCondition.parameters?.benchmark || "SPY"), benchmarkUrl = new URL(`https://data.alpaca.markets/v2/stocks/${encodeURIComponent(benchmark)}/bars`); benchmarkUrl.searchParams.set("timeframe", timeframe); benchmarkUrl.searchParams.set("start", start); benchmarkUrl.searchParams.set("limit", "1000"); benchmarkUrl.searchParams.set("feed", "iex"); benchmarkBars = (await alpaca(benchmarkUrl.toString(), apiKey, apiSecret)).bars || []; }
      if (validateOptions) { await optionOrder(bot, bars, apiKey, apiSecret, admin, `bg-validation-${bot.id.slice(0, 12)}`); summary.optionValidated++; break; }
      const conditionResults = conditions.map((condition: any) => ({ type: condition.type, timeframe: condition.timeframe, passed: matches(condition, bars, { benchmarkBars }), parameters: condition.parameters })); const hit = conditions.length > 0 && (bot.start_condition?.operator === "OR" ? conditionResults.some((item: any) => item.passed) : conditionResults.every((item: any) => item.passed)); if (!hit) { const passed = conditionResults.filter((item: any) => item.passed).length; await setStatus("conditions_not_met", `${passed} of ${conditionResults.length} start conditions passed`, { conditions: conditionResults, last_price: bars.at(-1)?.c, timeframe }); summary.skipped++; continue; } summary.matched++; await setStatus("conditions_met", "All required start conditions passed; checking order safety", { conditions: conditionResults, last_price: bars.at(-1)?.c, timeframe });
      const bucket = Math.floor(Date.now() / Math.max(Number(bot.cooldown_seconds || 300) * 1000, 300000)); const clientOrderId = `bg-${bot.id.slice(0, 12)}-${bucket}`;
      const existing = await fetch(`https://paper-api.alpaca.markets/v2/orders:by_client_order_id?client_order_id=${clientOrderId}`, { headers: { "APCA-API-KEY-ID": apiKey, "APCA-API-SECRET-KEY": apiSecret } }); if (existing.ok) { await setStatus("duplicate_blocked", "This cycle's order was already submitted; duplicate blocked"); summary.skipped++; continue; }
      const { data: steps } = await admin.from("bg_averaging_steps").select("order_amount").eq("bot_id", bot.id).eq("step_number", 0).maybeSingle(); const installments=Number(bot.start_condition?.strategy_config?.installments||1),currentExposure=positions.filter((p:any)=>p.symbol===bot.symbol).reduce((sum:number,p:any)=>sum+Math.abs(Number(p.market_value||0)),0),remaining=Math.max(0,Number(bot.max_allocation)-currentExposure); const notional = Math.min(Number(steps?.order_amount || Number(bot.max_allocation)/installments), remaining);if(notional<1){await setStatus("allocation_full","Maximum allocation is already deployed",{current_exposure:currentExposure,max_allocation:Number(bot.max_allocation)});summary.skipped++;continue;}
      const option = bot.asset_class === "option" ? await optionOrder(bot, bars, apiKey, apiSecret, admin, clientOrderId) : null; const orderRequest = option?.request || { symbol: bot.symbol, notional: notional.toFixed(2), side: bot.direction === "short" ? "sell" : "buy", type: "market", time_in_force: "day", client_order_id: clientOrderId };
      const order = await alpaca("https://paper-api.alpaca.markets/v2/orders", apiKey, apiSecret, { method: "POST", body: JSON.stringify(orderRequest) });
      const { data: run } = await admin.from("bg_bot_runs").insert({ bot_id: bot.id, user_id: bot.user_id, status: "running", metadata: { worker: "paper-runner" } }).select("id").single();
      const { data: trade } = await admin.from("bg_trades").insert({ run_id: run.id, user_id: bot.user_id, symbol: bot.symbol, status: "pending", side: bot.direction, quantity: 0 }).select("id").single();
      await admin.from("bg_orders").insert({ trade_id: trade.id, user_id: bot.user_id, broker_order_id: order.id, client_order_id: clientOrderId, symbol: bot.symbol, side: bot.direction === "short" ? "sell" : "buy", order_type: option ? "limit" : "market", notional: option ? null : notional, limit_price: option ? Number(orderRequest.limit_price) : null, status: order.status, raw_response: order, submitted_at: new Date().toISOString() });
      await admin.from("bg_bot_events").insert({ bot_id: bot.id, run_id: run.id, user_id: bot.user_id, event_type: "paper_order_submitted", message: `Submitted ${bot.symbol} ${option ? "option" : "stock"} paper order`, details: { broker_order_id: order.id, client_order_id: clientOrderId, notional: option ? null : notional, option_symbols: option?.symbols, max_risk: option?.risk } }); await setStatus("order_submitted", `Submitted ${option ? "option" : "stock"} paper order`, { broker_order_id: order.id, client_order_id: clientOrderId }); summary.submitted++; if (option) summary.optionOrders++;
    } catch (e) { summary.errors++; const message = e instanceof Error ? e.message : "Runner error"; await setStatus("error", message); await admin.from("bg_bot_events").insert({ bot_id: bot.id, user_id: bot.user_id, event_type: "runner_error", severity: "error", message }); }
  }
  return json(summary);
});
