import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type": "application/json", "Cache-Control": "private, max-age=300" } });
const fromB64 = (value: string) => Uint8Array.from(atob(value), (char) => char.charCodeAt(0));
async function decrypt(value: string, iv: string, key: CryptoKey) { return new TextDecoder().decode(await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromB64(iv) }, key, fromB64(value))); }
async function getJson(url: string, apiKey: string, apiSecret: string) { const response = await fetch(url, { headers: { "APCA-API-KEY-ID": apiKey, "APCA-API-SECRET-KEY": apiSecret } }); if (!response.ok) throw new Error(`Alpaca request failed (${response.status})`); return response.json(); }
async function optionalJson(url: string, apiKey: string, apiSecret: string) { try { return await getJson(url, apiKey, apiSecret); } catch { return null; } }
const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0;
const change = (bars: any[], sessions: number) => bars.length > sessions ? (Number(bars.at(-1).c) / Number(bars.at(-(sessions + 1)).c) - 1) * 100 : null;

Deno.serve(async (request) => {
  if (request.method === "OPTIONS") return new Response("ok", { headers: cors });
  try {
    const admin = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!, { auth: { persistSession: false } });
    const token = request.headers.get("Authorization")?.replace(/^Bearer\s+/i, ""); const { data: { user } } = await admin.auth.getUser(token); if (!user) return json({ error: "Authentication required" }, 401);
    const { symbol: rawSymbol } = await request.json(); const symbol = String(rawSymbol || "").toUpperCase().trim(); if (!/^[A-Z.]{1,10}$/.test(symbol)) return json({ error: "Valid ticker required" }, 400);
    const { data: connection } = await admin.from("bg_broker_connections").select("id").eq("user_id", user.id).eq("broker", "alpaca").eq("environment", "paper").eq("status", "connected").single(); if (!connection) return json({ error: "Connect Alpaca to load ticker information" }, 400);
    const { data: credential } = await admin.from("bg_broker_credentials").select("*").eq("connection_id", connection.id).single(); const raw = fromB64(Deno.env.get("BG_CREDENTIALS_KEY") || ""); const cryptoKey = await crypto.subtle.importKey("raw", raw, "AES-GCM", false, ["decrypt"]); const [apiKey, apiSecret] = await Promise.all([decrypt(credential.api_key_ciphertext, credential.api_key_iv, cryptoKey), decrypt(credential.api_secret_ciphertext, credential.api_secret_iv, cryptoKey)]);
    const end = new Date(), start = new Date(); start.setUTCDate(start.getUTCDate() - 100);
    const barsUrl = new URL(`https://data.alpaca.markets/v2/stocks/${encodeURIComponent(symbol)}/bars`); barsUrl.searchParams.set("timeframe", "1Day"); barsUrl.searchParams.set("start", start.toISOString()); barsUrl.searchParams.set("end", end.toISOString()); barsUrl.searchParams.set("adjustment", "all"); barsUrl.searchParams.set("feed", "iex"); barsUrl.searchParams.set("limit", "1000");
    const newsUrl = new URL("https://data.alpaca.markets/v1beta1/news"); newsUrl.searchParams.set("symbols", symbol); newsUrl.searchParams.set("sort", "desc"); newsUrl.searchParams.set("limit", "5"); newsUrl.searchParams.set("include_content", "false");
    const [barsData, snapshot, asset, newsData] = await Promise.all([getJson(barsUrl.toString(), apiKey, apiSecret), optionalJson(`https://data.alpaca.markets/v2/stocks/${encodeURIComponent(symbol)}/snapshot?feed=iex`, apiKey, apiSecret), optionalJson(`https://paper-api.alpaca.markets/v2/assets/${encodeURIComponent(symbol)}`, apiKey, apiSecret), optionalJson(newsUrl.toString(), apiKey, apiSecret)]);
    const bars = (barsData.bars || []).slice(-60); if (bars.length < 15) return json({ error: "Not enough recent market data for this ticker" }, 404);
    const returns = bars.slice(1).map((bar: any, index: number) => Number(bar.c) / Number(bars[index].c) - 1), mean = average(returns), variance = average(returns.map((value: number) => (value - mean) ** 2)), annualizedVolatility = Math.sqrt(variance) * Math.sqrt(252) * 100;
    const trueRanges = bars.slice(1).map((bar: any, index: number) => Math.max(Number(bar.h) - Number(bar.l), Math.abs(Number(bar.h) - Number(bars[index].c)), Math.abs(Number(bar.l) - Number(bars[index].c)))), atr14 = average(trueRanges.slice(-14)), lastClose = Number(bars.at(-1).c);
    let peak = Number(bars[0].c), maxDrawdown = 0; bars.forEach((bar: any) => { const close = Number(bar.c); peak = Math.max(peak, close); maxDrawdown = Math.max(maxDrawdown, (peak - close) / peak * 100); });
    const volumes = bars.slice(-20).map((bar: any) => Number(bar.v || 0)), averageVolume = average(volumes), bid = Number(snapshot?.latestQuote?.bp || 0), ask = Number(snapshot?.latestQuote?.ap || 0), midpoint = bid && ask ? (bid + ask) / 2 : 0;
    const news = (newsData?.news || []).map((item: any) => ({ id: item.id, headline: item.headline, summary: item.summary, source: item.source, author: item.author, created_at: item.created_at, url: item.url, symbols: item.symbols }));
    return json({ symbol, asset: asset ? { name: asset.name, exchange: asset.exchange, status: asset.status, tradable: asset.tradable, fractionable: asset.fractionable, shortable: asset.shortable, easy_to_borrow: asset.easy_to_borrow, options_enabled: asset.options_enabled ?? asset.optionable } : null, market: { price: Number(snapshot?.latestTrade?.p || snapshot?.minuteBar?.c || lastClose), previous_close: Number(snapshot?.prevDailyBar?.c || bars.at(-2)?.c), change_5d_pct: change(bars, 5), change_20d_pct: change(bars, 20), annualized_volatility_pct: annualizedVolatility, atr_14: atr14, atr_14_pct: atr14 / lastClose * 100, max_drawdown_60d_pct: maxDrawdown, average_volume_20d: averageVolume, latest_volume: Number(bars.at(-1).v || 0), relative_volume: averageVolume ? Number(bars.at(-1).v || 0) / averageVolume : null, bid, ask, spread_pct: midpoint ? (ask - bid) / midpoint * 100 : null, as_of: snapshot?.latestTrade?.t || bars.at(-1).t, feed: "iex" }, news, methodology: "Risk metrics use up to 60 adjusted Alpaca IEX daily bars; volatility is annualized from close-to-close returns; drawdown is close-to-close." });
  } catch (error) { return json({ error: error instanceof Error ? error.message : "Unable to load ticker insights" }, 500); }
});
